# Generated by Django 5.2.3 on 2025-07-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_bio_alter_profile_budget_and_more'),
    ]

    operations = [
    ]
